---
- name: Install Dependencies
  apt: pkg={{ item }} state=present
  sudo: yes
  with_items:
    - python
    - python-dev
    - python-pip
    - libffi-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev

- name: Install mitmproxy
  pip: name=mitmproxy state=present
  sudo: yes
